added support for turbinia recipes
log2timeline/dftimewolf pull request #535
Opened 2022-02-16 21:31 UTC by jleaniz

This pull request accomplishes two things:

- Uses new turbinia client methods to create requests and recipes
- Allows a user to specify a Turbinia recpie name (e.g. triage-linux) as a parameter for dfTimewolf recipes that utilize Turbinia for processing.

This PR is a work in progress.

Fixes #496

2022-02-16 21:42 UTC, jleaniz commented
Tests are failing because the version of Turbinia being used for the tests does not contain the new methods in the turbinia.client module

2022-02-17 02:33 UTC, aarontp commented
FYI, a new release of Turbinia  (`20220216`) has been cut as of this afternoon, so I think we just need to update the dftimewolf dependencies appropriately.

2022-02-17 03:25 UTC, ramo-j commented
I'm aware this PR is still in draft, so apologies if I'm jumping the gun, but I notice that in some of the recipe updates the `turbinia_recipe` option is required, and optional in some. Is this deliberate? Optional across the board makes sense to me, if there's a reasonable default recipe.

2022-02-17 15:09 UTC, jleaniz commented
hey @ramo-j thanks for pointing that out. Yeah, still WIP, the turbinia_recipe arg will be optional for the time being, the default recipe has not been modified as of now but this would just give the ability to specifcy a turbinia recipe if desired.

2022-03-21 15:21 UTC, jleaniz commented
@tomchop I believe some checks are fialing due to using an older Turbinia version. The method in question was introduced in version [20220216](https://github.com/google/turbinia/releases/tag/20220216)

```
************* Module tests.lib.processors.turbinia_gcp
tests/lib/processors/turbinia_gcp.py:56:4: E1101: Instance of 'TurbiniaCeleryClient' has no 'create_request' member (no-member)
```

2022-03-22 09:21 UTC, tomchop requested changes

2022-03-22 09:21 UTC, tomchop commented on Pipfile
> +turbinia = "20220321"
Pleas generate a new `requirements.txt`

```
pipenv lock -r > requirements.txt
```

2022-03-22 09:21 UTC, tomchop commented on tests/lib/processors/turbinia_artifact.py
> +from turbinia.message import TurbiniaRequest
Same thing for the other tests in `turbinia_gcp.py`

2022-03-22 16:27 UTC, jleaniz commented on Pipfile
> +turbinia = "20220321"
Done

2022-03-22 16:28 UTC, jleaniz commented on tests/lib/processors/turbinia_artifact.py
> +from turbinia.message import TurbiniaRequest
Done

2022-03-28 16:21 UTC, tomchop approved these changes

2022-03-28 16:29 UTC, jleaniz commented
Merge.

2022-03-28 16:29 UTC, merged