Filter for meeting_id delimiter
log2timeline/dftimewolf pull request #538
Opened 2022-02-17 18:02 UTC by jkppr

Added a filter that removes the '-' delimiters form the meeting_id when used with the workspace_meet_ts recipe. Additionally I added the info to use the meeting_id without delimiters to the documentations and help as well.

2022-02-17 18:22 UTC, tomchop requested changes

2022-02-17 18:22 UTC, tomchop commented on dftimewolf/lib/collectors/workspace_audit.py
> +      if '-' in filter_expression:
Maybe combine these in an `and`?

2022-02-17 18:22 UTC, tomchop commented on dftimewolf/lib/collectors/workspace_audit.py
> +            'Found \'-\' delimiter in the meeting_id and removed it!')
```suggestion
            "Found '-' delimiter in the meeting_id and removed it!")
```

is slightly more readable. You're allowed to infringe the always-use-the-same-quote-type rules when you are including quotes in a string :)

2022-02-18 10:17 UTC, jkppr commented
Thanks for the input. I adjusted the code accordingly.

2022-02-18 13:40 UTC, tomchop approved these changes

2022-02-18 13:40 UTC, merged