Bigfiles
log2timeline/dftimewolf pull request #845
Opened 2024-03-23 11:03 UTC by tomchop

2024-04-05 19:55 UTC, Onager requested changes

2024-04-05 19:55 UTC, Onager commented on dftimewolf/lib/collectors/grr_hosts.py
> +  ) -> None:
Please add docstrings here for the args

2024-04-05 19:55 UTC, Onager commented on dftimewolf/lib/collectors/grr_hosts.py
> +    self, client: Client, pathspecs: Client.Flow, flow_output_dir: str
Please add docstring

2024-04-05 19:55 UTC, Onager commented on dftimewolf/lib/collectors/grr_hosts.py
> +  def _DownloadTimeline(
Please add docstrings

2024-04-05 19:55 UTC, Onager commented on dftimewolf/lib/collectors/grr_hosts.py
>    # TODO: change object to more specific GRR type information.
This looks like it no longer applies, as the type hint here has a more up-to-date definition - while you're here, please update the docstring and remove the todo

2024-04-05 19:55 UTC, Onager commented on dftimewolf/lib/collectors/grr_hosts.py
> +    self, client: Client, pathspecs: Client.Flow, flow_output_dir: str
Type is wrong for "pathspecs" here, should be a list of pathspecs

2024-04-05 19:55 UTC, Onager commented on dftimewolf/lib/collectors/grr_hosts.py
> +    if not os.path.isdir(flow_output_dir):
This check seems redundant now you're passing exist_ok - remove?

2024-04-17 12:05 UTC, tomchop commented on dftimewolf/lib/collectors/grr_hosts.py
> +  ) -> None:
Done.

2024-04-17 12:52 UTC, Onager submitted a review, later dismissed

2024-04-17 13:56 UTC, tomchop commented
Got an LGTM, merging

2024-04-17 13:56 UTC, merged